### ISSUE TITLE
Service Always Deletes Tags After Un-deploying

### ISSUE THREAD

**Issue by agomez08** [NIVeriStandAdd-Ons/Data-Publishing-Service#4]
Service calls into the Delete Tag.vi when shutting down, which causes the tags to be completely deleted from the server. This is not very convenient if you had spent some time configuring settings for the tag like retention, which would be gone once you un-deploy. 

It would be nice to allow keeping the tags after un-deploying by calling Close Tag.vi instead of Delete Tag.vi. This could be configurable from the INI.

**Comment by cdaughters** [comment]
@agomez08 I ran into this also, it looks like the tags get deleted in the "Tags.Destroy" case. Did you have any luck with this? I think it would be nice to add parameters to the .ini file to either enable tag history (T/F) or delete tags on undeploy (T/F). What did you end up doing in your pull request?

Some additional context: With the new Tile format dashboards, graphs only display if they have history enabled. I deployed VeriStand (which created all my tags), changed them in SystemLink Tag Viewer to enable history, then undeployed and all the tags were deleted. This makes my dashboard useless unless I go back and enable history.

**Comment by agomez08** [comment]
HI @cdaughters 
My pull request does handle this through a setting on the INI file. If True, the service deletes used tags in the server when undeploying. If False, the service just closes reference to tags without deleting them from server.

Here is the PR: https://github.com/NIVeriStandAdd-Ons/Data-Publishing-Service/pull/5
